### ISSUE TITLE
No module named 'utility'

### ISSUE THREAD

**Issue by chengjianhong** [heshida01/MRMD2.0#1]
Hi, there is a error. and I have installed the utility, but it still exists the following error.

> Traceback (most recent call last):
>   File "mrmd2.0.py", line 6, in <module>
>     from feature_Rank import feature_rank
>   File "/root/userfolder/workspace_python/MRMD2.0/feature_Rank.py", line 15, in <module>
>     import  feature_selection.lasso2
>   File "/root/userfolder/workspace_python/MRMD2.0/feature_selection/lasso2.py", line 1, in <module>
>     from feature_selection.thePrecisionLasso.models.PrecisionLasso import PrecisionLasso
>   File "/root/userfolder/workspace_python/MRMD2.0/feature_selection/thePrecisionLasso/models/PrecisionLasso.py", line 4, in <module>
>     from utility.cg import solve_cg, A_trace, norm, logisticRegressionGradientSolver
> ModuleNotFoundError: No module named 'utility'

**Comment by heshida01** [comment]
Try changing the fourth line of that file to   “from  feature_selection.thePrecisionLasso.utility.cg import solve_cg, A_trace, norm, logisticRegressionGradientSolver“”
